/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.havidalbar.calculatorTDD;

class Calculator{
	private double result;

	public Double cancel(){
		return this.result = 0.0;
	}

	public Double add(int number){
		return this.result += number;
	}

	public Double subtract(int number){
		return this.result -= number;
	}

	@Override
	public String toString() {
		return String.valueOf(this.result);
	}
}

public class App {
	public String getGreeting() {
		return "Hello Havid!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
	}
}
