/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.havidalbar.calculatorTDD;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	Calculator calculate = new Calculator();

	@Test public void testAppHasAGreeting() {
		App classUnderTest = new App();
		assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	}

	@Test public void testAppOperationToString() {
		assertEquals("0.0", calculate.toString());
	}
	@Test public void testAppOperationCancel() {
		calculate.cancel();
		assertEquals("0.0", calculate.toString());
	}

	@Test public void testAppOperationAdd() {
		int number = 4;
		calculate.add(number);
		assertEquals("4.0", calculate.toString());
	}

	@Test public void testAppOperationSubtract() {
		int number = 1;
		calculate.subtract(number);
		assertEquals("-1.0", calculate.toString());
	}
}
